name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup key
      - run: set -eu
      - run: mkdir "/root/.ssh"
      - run: echo "${{ secrets.id_rsa }}" > "/root/.ssh/id_rsa"
      - run: chmod 600 "/root/.ssh/id_rsa"
      # Deploy
      - run: rsync -e "ssh -p 20022 -i /root/.ssh/id_rsa -o StrictHostKeyChecking=no" --archive --compress --delete . root@172.105.131.155:/root/var/www/site1
